// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEXVPOg9zhCZ_wIczsQstLSjw2UXG3I3c',
    appId: '1:351865226329:web:a7ee4a700cd43d9c5b9d48',
    messagingSenderId: '351865226329',
    projectId: 'modul3-codelab-2eac6',
    authDomain: 'modul3-codelab-2eac6.firebaseapp.com',
    storageBucket: 'modul3-codelab-2eac6.appspot.com',
    measurementId: 'G-DGZ86DNWJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDySQ2YuWJGH39dqeA0IVv5T23M_FDDFz0',
    appId: '1:351865226329:android:4331fc2a6b169fbd5b9d48',
    messagingSenderId: '351865226329',
    projectId: 'modul3-codelab-2eac6',
    storageBucket: 'modul3-codelab-2eac6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByg9r-oBIsTkBrRvttheiGQfwEXDpP5OE',
    appId: '1:351865226329:ios:c068b2f12ba1f7045b9d48',
    messagingSenderId: '351865226329',
    projectId: 'modul3-codelab-2eac6',
    storageBucket: 'modul3-codelab-2eac6.appspot.com',
    iosBundleId: 'xyz.reparin.tugas1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByg9r-oBIsTkBrRvttheiGQfwEXDpP5OE',
    appId: '1:351865226329:ios:c068b2f12ba1f7045b9d48',
    messagingSenderId: '351865226329',
    projectId: 'modul3-codelab-2eac6',
    storageBucket: 'modul3-codelab-2eac6.appspot.com',
    iosBundleId: 'xyz.reparin.tugas1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEXVPOg9zhCZ_wIczsQstLSjw2UXG3I3c',
    appId: '1:351865226329:web:49410ca309bc82605b9d48',
    messagingSenderId: '351865226329',
    projectId: 'modul3-codelab-2eac6',
    authDomain: 'modul3-codelab-2eac6.firebaseapp.com',
    storageBucket: 'modul3-codelab-2eac6.appspot.com',
    measurementId: 'G-6QK4QZ7KV1',
  );
}